# Generated by Django 3.1.3 on 2020-11-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='donation_categories', to='donationApp.Category'),
        ),
    ]
