# Generated by Django 3.1.3 on 2020-11-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0003_auto_20201121_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False, verbose_name='Odebrane przez kuriera'),
        ),
    ]
